# http://stackoverflow.com/questions/9321153/rails-database-setup-on-travis-ci

# Language to use is Ruby
language: ruby

# Database Environment is mysql
env:
  - DB=mysql

# Use Ruby 2.0.0
rvm:
  - 2.0.0

# Commands to run before tests. Create DB config file and create database.
before_script:
  - cp config/database.yml.skel config/database.yml
  - cp config/initializers/devise.rb.example config/initializers/devise.rb
  - cp config/initializers/secret_token.rb.example config/initializers/secret_token.rb
  - RAILS_ENV=test bundle exec rake db:create
  - "export DISPLAY=:99.0"
  - bundle exec rake db:test:prepare